# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
# CodeRabbit Configuration - Corrected based on official template
# Reference: https://docs.coderabbit.ai/reference/configuration

# Global language setting for reviews
language: "en-US"

reviews:
  # Automatically review new pull requests
  auto_review:
    enabled: true
    drafts: false # Do not review draft PRs

  # Filter which files to review.
  # These patterns are crucial for avoiding noise.
  path_filters:
    - "!node_modules/**"
    - "!.git/**"
    - "!*.log"
    - "!*.tmp"
    - "!dist/**"
    - "!build/**"

  # Enable specific linters and analysis tools
  tools:
    # For shell script analysis
    shellcheck:
      enabled: true
    # For Markdown file analysis
    markdownlint:
      enabled: true

# Knowledge base settings to improve review context
knowledge_base:
  # Learn from the repository itself
  learnings:
    scope: 'local'

  # Learn from specific guideline files in the repository
  code_guidelines:
    enabled: true
    filePatterns:
      - "AGENTS.md"
      - "GEMINI.md"
      - "specs/*.md"