# CodeRabbit Configuration
# See: https://docs.coderabbit.ai/guides/configure-coderabbit

# General settings
reviews:
  auto_review: true
  draft_reviews: false
  ignore_patterns:
    - '*.log'
    - '*.tmp'
    - 'node_modules/**'
    - '.git/**'
  languages:
    bash:
      enhanced_review: true
      security_analysis: true
    markdown:
      documentation_review: true

# Issue creation settings (Pro feature)
issue_creation:
  auto_create: true
  platforms:
    - github
  templates:
    bug:
      title: '🐛 Bug found during review'
      labels: ['bug', 'coderabbit-created']
    improvement:
      title: '💡 Improvement suggestion'
      labels: ['enhancement', 'coderabbit-created']

# Comment settings
comments:
  concise_mode: true
  skip_trivial: true
  focus_areas:
    - security
    - performance
    - maintainability
    - shell-best-practices

# Integration settings
integrations:
  github_actions: true
  status_checks:
    enabled: true
    block_merge_on_failure: false

# Learning settings
learning:
  repository_context: true
  focus_domains:
    - 'termux'
    - 'android'
    - 'shell-scripting'
    - 'ai-integration'
