# ====================================
# Powerlevel10k Classic Style Configuration
# Termux-Dev Inspired - Clean Block Style
# ====================================

# Generated by Powerlevel10k configuration wizard.
# Classic Style Configuration - Based on termux-dev colors

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # CLASSIC STYLE CONFIGURATION
  # Based on the image: block style with blue/cyan theme, single line

  # The list of segments shown on the left
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
  )

  # The list of segments shown on the right - minimal like image
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    ram                     # memory percentage only
  )

  # Single line prompt (like the image)
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=false
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=''
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=''

  # =========================[ Visual Style ]========================

  # Classic block style separators
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

  # Visual style
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Background and foreground
  typeset -g POWERLEVEL9K_BACKGROUND=none

  # =========================[ Directory ]===========================

  # Directory colors - Blue theme like in image
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=255      # White text
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=33       # Blue background (similar to image)
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=255
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255

  # Directory separators - using / instead of >
  typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR='/'
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER='/'

  # Directory icons - clean and simple
  typeset -g POWERLEVEL9K_DIR_HOME_ICON='~'
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_ICON=''
  typeset -g POWERLEVEL9K_DIR_DEFAULT_ICON=''
  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_ICON='🔒'

  # Directory truncation
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40

  # =========================[ VCS (Git) ]===========================

  # Git status colors - Green theme for git like in image
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=255
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=28      # Green background
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=255
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=208  # Orange for changes
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=255
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=208   # Orange for changes

  # Git icons - clean
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON=''
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'

  # =========================[ RAM ]==============================

  # RAM colors - Cyan theme like in image
  typeset -g POWERLEVEL9K_RAM_FOREGROUND=0            # Black text
  typeset -g POWERLEVEL9K_RAM_BACKGROUND=123          # Cyan background
  typeset -g POWERLEVEL9K_RAM_VISUAL_IDENTIFIER_EXPANSION='%fRAM'

  # =========================[ Status ]==============================

  # Hide OK status, only show errors
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=255  # White
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=196  # Red
  typeset -g POWERLEVEL9K_STATUS_ERROR_ICON='❌'

  # =========================[ Instant Prompt ]======================

  # Instant prompt mode.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'